# Generated by Django 4.1.1 on 2022-11-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.URLField(null=True)),
                ('descricao', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('repr_senha', models.CharField(max_length=50)),
                ('ingresso', models.DateField()),
                ('curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('entrada_equipe', models.DateField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipes.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipes.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipes.equipe')),
            ],
        ),
    ]
