# Generated by Django 4.1.2 on 2022-12-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='equipe',
        ),
        migrations.AddField(
            model_name='membro',
            name='equipes',
            field=models.ManyToManyField(to='equipes.equipe'),
        ),
    ]
