# Generated by Django 4.1.2 on 2022-12-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0002_remove_membro_equipe_membro_equipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='logo',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='link',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
