# Generated by Django 4.1.1 on 2022-12-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipes", "0003_alter_equipe_logo_alter_foto_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="tipo",
            field=models.CharField(default="event", max_length=255),
            preserve_default=False,
        ),
    ]
